### ISSUE TITLE
append form data to submit() via options param

### ISSUE THREAD

**Issue by jywarren** [bevacqua/bureaucracy#2]
I'm looking to submit some extra data along with the files I'm uploading (in `woofmark`). It looks like this'd be possible by unioning an `options.formData` object with the `req` object here:

https://github.com/bevacqua/bureaucracy/blob/master/bureaucracy.js#L44-L52

What do you think? Happy of course to submit a PR.

**Comment by bevacqua** [comment]
Iterating over that object and adding the values to `form`? Sounds good to me.

**Comment by jywarren** [comment]
Would it then be possible to create an options hash in `woofmark`'s
constructor, which would end up being `options.images.options` (odd),
passed into the `bureaucracy` constructor? It's a little strange, so if you
have a cleaner idea I'd love to hear. Thanks a lot!

**Comment by bevacqua** [comment]
In woofmark:

``` js
options.images.formData
```

**Comment by jywarren** [comment]
Great. Submitted PR #3 --

**Comment by jywarren** [comment]
Complete in #3!
